version: "3.7"
services:
  postgis:
    image: docker.io/znmeb/postgis
    network_mode: "host"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  rstats:
    image: docker.io/znmeb/rstats
    network_mode: "host"
    environment:
      - PASSWORD=${RSTUDIO_PASSWORD}
  pgadmin4:
    image: docker.io/znmeb/pgadmin4
    network_mode: "host"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
