version: '3.4'
services:
  rstats:
    build:
      context: .
      dockerfile: Dockerfile.rstats
    image: rstats

    # RStudio password is just called "PASSWORD"
    environment:
      - PASSWORD
    ports:
      - 8787:8787
  postgis:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    image: postgis
    environment:
      - POSTGRES_PASSWORD
    ports:
      - 5439:5432
    command: [ "postgres", "-c", "max_wal_size=2GB" ]
  pgadmin4:
    image: docker.io/dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - 8686:80
